---

- name: Creating Admin User {{ uusername }}
  user:
    name: "{{ uusername }}" 
    password: "{{ upassword | password_hash('sha512') }}"
    groups: sudo
    append: yes
  when: assigned_role == "yes"

- name: Creating Non-Admin User {{ uusername }}
  user:
    name: "{{ uusername }}"
    password: "{{ upassword | password_hash('sha512') }}"
  when: assigned_role == "no"

- name: Expire Password For {{ uusername }}
  shell: chage -d 0 "{{ uusername }}"
